In [1]:
import numpy as np
arr=np.array([4,6,7,2,9,11,20])
print(np.mean(arr))

8.428571428571429


In [2]:
print(np.std(arr))

5.473498303048005


In [7]:
ary=np.array([2,4,56,78,90,0])
print(np.all(ary))

False


In [4]:
ar1=np.array([2,4,35,67,89,10])
print(np.all(ar1))

True


In [12]:
ar1=np.random.random((3,3,3))

In [13]:
ar1

array([[[0.17204752, 0.05364912, 0.71957343],
        [0.40209883, 0.43196902, 0.06645334],
        [0.04927829, 0.3881779 , 0.49521693]],

       [[0.16241411, 0.57012466, 0.17779389],
        [0.51523632, 0.97574536, 0.17799043],
        [0.57840606, 0.92420916, 0.03283812]],

       [[0.81141965, 0.23017325, 0.93572758],
        [0.13968794, 0.86782795, 0.20070624],
        [0.21972023, 0.85194635, 0.57010203]]])

In [15]:
a1=np.array([4,5,2,1,9])
a2=np.array([6,8,0,7,4])
print(np.cov(a1,a2))

[[ 9.7  0.5]
 [ 0.5 10. ]]


In [17]:
arry=np.array([20,-10,-57.25,70.65])
print(np.absolute(arry))

[20.   10.   57.25 70.65]
